name: notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.0
  freezed_annotation: ^0.7.1
  flutter_bloc: ^3.2.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.2
  injectable: ^0.3.0
  get_it: ^4.0.1


dev_dependencies:
  build_runner:
  freezed: ^0.10.6
  injectable_generator: ^0.3.4

  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
